### ISSUE TITLE
Declarative UI

### ISSUE THREAD

**Issue by Cryrivers** [xch91/underscore-multifile-template#1]
``` javascript
    var ue = UsmfEngine();
    ue("tpl1.html", data1, $("#tpl-test1"));
    ue("tpl2.html", data2, $("#tpl-test2"));
    ue("tpl1.html", data3, $("#tpl-test3"));
```

The code above is imperative and blended into the app logic, which should be declarative.

**Comment by alyoshark** [comment]
I think it is possible only when two way data binding is introduced or use ES6 object.observe. Any suggestions?
